server:
  port: 8080

# mysql-connector-java 6.0.x 及以上版本配置
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.79.158.192:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root1234
    initialization-mode: always
    schema: classpath:sql/boot.sql
    data:
  # redis 服务端相关配置
  redis:
    # 服务器地址
    host: 120.79.158.192
    # 端口号
    port: 6379
    # 使用的数据库，默认选择下标为0的数据库
    database: 0
    # 密码，默认为 null
    password:
    # 客户端超时时间,默认是2000ms
    timeout: 2000

    # lettuce 客户端配置(从 Spring Boot 2.x 开始，推荐使用 lettuce 客户端)
    lettuce:
      pool:
        # 建立连接最大等待时间，默认1ms，超出该时间会抛异常。设为-1表示无限等待，直到分配成功。
        max-wait: 1ms
        # 最大连连接数，默认为8，负值表示没有限制
        max-active: 8
        # 最大空闲连接数,默认8。负值表示没有限制
        max-idle: 8
        # 最小空闲连接数,默认0。
        min-idle: 0
      # 设置关闭连接的超时时间
      shutdown-timeout: 100ms
  # 配置缓存的类型
  cache:
    type: redis

    #hikari数据库连接池
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 3 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
logging:
  level:
    com.ywl.dao: debug
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml